### PR TITLE
add possibility for dev release

### PR DESCRIPTION
**Pull request by srmnitc**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by srmnitc** [comment]
Adds the possibility to add versions tagged with `*.dev.*` in their release into the `dev` channel. The package can then be installed by:
```
conda install -c conda-forge/label/pyiron_atomistics_dev -c conda-forge pyiron_atomistics
```
or added in the environment file by:
```
dependencies:
  - conda-forge/label/pyiron_atomistics_dev::pyiron_atomistics
```

**Comment by srmnitc** [comment]
@jan-janssen Somehow it doesnt pick up the pre-release package from pypi. Could you please check what could be a reason? The other option is to build the pre-release packages from github release directly. What do you think about this?

**Comment by jan-janssen** [comment]
> Edit: Somehow pypi was removing the second dot after dev. We should try to understand if there are any other restrictions in the version names.

https://pythonpackaging.info/07-Package-Release.html#Versioning-your-code

**Comment by srmnitc** [comment]
merging as tests pass, also see github.com/pyiron/pyiron_base#1155

**Comment by niklassiemer** [comment]
Sorry, I tend to ignore review requests by conda-forge feedstocks. A mention is better in these cases xD 
I had seen the PR, however, and it looked like a normal release except for the chanel. Since this is exactly the part I am not familiar with, I did not leave a comment.

**Comment by jan-janssen** [comment]
There seems to be an issue with the `pyiron_atomistics` package as the backwards compatibility tests start to fail on `pyiron_base`: 

```
      /usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/setuptools/dist.py:510: SetuptoolsDeprecationWarning: Invalid version: '0.3.0.dev.0.post.dev11'.
      !!
      
              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************
      
      !!
```

**Comment by jan-janssen** [comment]
In addition the development release `pyiron_atomistics-0.3.0.dev0-pyhd8ed1ab_0.conda` is published to the main channel: 
https://anaconda.org/conda-forge/pyiron_atomistics/files

**Comment by jan-janssen** [comment]
I fixed the label by rerendering the recipe on the `dev` branch https://github.com/conda-forge/pyiron_atomistics-feedstock/pull/111 . Still the issue with versioneer creating incorrect version numbers remains.

**Pull request merged**
